name: Deploy to Github Pages

# Run Workflow on every push to the main branch
on:
  push:
    branches: [master]

jobs:
  deploy-to-github-pages:
    # use ubuntu-lates image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses Github's Checkout action to checkout the code from the main branch
      - uses: actions/checkout@v4
      # sets up .NET SDK 5.0.x
      - name: Setup .NET SDK 5.0.X
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      # publishes Blazor project to the release folder
      - name: Publish .NET Project
        run: dotnet publish BlazorApp1/BlazorApp1.csproj -c Release -o release --nologo
      # changes the base-tag in index.html from '/' to 'BlazorAppWithOAuth' to match Github Pages
      - name: Chnage base-tag in index.html from / to BlazorAppWithOAuth
        run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorAppWithOAuth\/" \/>/g' release/wwwroot/index.html
      # copy index.html to 404.html to server the same file when a file is not found
      - name: copy Index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      # add .nojekyll file to tell github pages to not treat this as a Jekyll project. (Alows files and folders starting with a underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      # publish 222root directory to Github pages
      - name: Commit wwwroot to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          branch: gh-pages # The Branch the action should deploy to.
          folder: release/wwwroot # the folder the action should deploy

