name: Github Pages - Deploy

env:
  SOURCE_DIR: BlazorApp1
  PUBLISH_DIR: BlazorApp1/release/wwwroot

# Run Workflow on every push to the main branch
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [deploy/gh-pages]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK 8.0.X
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Tools
        run: dotnet workload install wasm-tools

        # https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore
      - name: Restore dependenices
        run: dotnet restore

      - name: Publish .NET Project
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          dotnet restore
          dotnet publish BlazorApp1.csproj -c Release -o release --nologo --no-restore

      # Upload intermediate result so that we can inspect it
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ENV.PUBLISH_DIR}}
          retention-days: 1

      # changes the base-tag in index.html from '/' to 'BlazorAppWithOAuth' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to BlazorAppWithOAuth
        working-directory: ${{env.PUBLISH_DIR}}
        run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorAppWithOAuth\/" \/>/g' index.html

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        working-directory: ${{env.PUBLISH_DIR}}
        run: cp index.html 404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        working-directory: ${{env.PUBLISH_DIR}}
        run: touch .nojekyll

      # Upload intermediate result so that we can inspect it
      - uses: actions/upload-artifact@v4
        with:
          name: build-processed
          path: ${{ENV.PUBLISH_DIR}}
          retention-days: 1

      # publishes wwwroot directory to GitHub Pages
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: live/gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ${{env.PUBLISH_DIR}}
